
FROM node:18-alpine AS development  # Optimized base image

# Install dependencies 
WORKDIR /app
COPY package*.json ./ 
RUN npm install --silent 

# Copy project files
COPY . .

# Start the development server
CMD ["npm", "run", "start"]