version: '3.8'

services: 
  portfolio:  
    container_name: portfolio  
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount project code for development
      - /app/node_modules  # Exclude node_modules for efficiency
    ports:
      - '3005:3000'  #map ports
 