version: '3.8'
services:
  portfolio:  
    container_name: portfolio  # This is optional, but helps you identify the container easily.
    image: portfolio:latest 
    env_file:
      - env.local
    volumes:
      - .:/app  
      - /app/node_modules  
    ports:
      - '3000:3000' 
 